# Operating system (build VM template)
os: Visual Studio 2017

version: 0.1-branch-{branch}-build-{build}

branches:
  only:
    - master

environment:
  matrix:
    - toolchain: "Windows-x86_64"
    - toolchain: "Windows-x86"
    - toolchain: "WinStore-x86"
    - toolchain: "WinStore-x86_64"
    - toolchain: "WinStore-ARM"

clone_folder: c:\projects\ds2
shallow_clone: true

platform: x64
configuration: Release

install:
  - C:\cygwin\setup-x86.exe
      -qnNdO
      -R C:/cygwin
      -s http://cygwin.mirror.constant.com
      -l C:/cygwin/var/cache/setup
      -P bison -P flex

build_script:
  - mkdir "C:\projects\ds2\build"
  - set PATH=%PATH%;C:\cygwin\bin
  - echo Running cmake...
  - cd c:\projects\ds2\build
  - cmake -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=../Support/CMake/Toolchain-%toolchain%.cmake ..
  - msbuild /p:Configuration=Release ds2.vcxproj

test: off
